CREATE TABLE "departements" (
	"id"	INTEGER NOT NULL UNIQUE,
	"departement"	TEXT NOT NULL,
	"approbe_par"	TEXT NOT NULL,
	"montant"	TEXT NOT NULL,
	"last_update"	REAL NOT NULL DEFAULT (datetime('now', 'localtime')),
	PRIMARY KEY("id" AUTOINCREMENT)
);

CREATE TABLE "liste_de_po" (
	"id"	INTEGER NOT NULL UNIQUE,
	"numero_de_po"	NUMERIC NOT NULL,
	"fournisseur"	TEXT NOT NULL,
	"demande_par"	TEXT,
	"description"	TEXT,
	"commentaire"	TEXT,
	"statut"		TEXT,
	"approbe_par"	TEXT,
	"last_update"	REAL NOT NULL DEFAULT (datetime('now', 'localtime')),
	FOREIGN KEY("approbe_par") REFERENCES "departements",
	PRIMARY KEY("id" AUTOINCREMENT)
);

INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('1', 'Finance', 'Patrick Clouâtre', 'Sans Limite', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('2', 'Finance', 'Amélie Dubois', 'CAD$24,999', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('3', 'Communications', 'Florence Turpault-Desroches', 'Sans Limite', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('4', 'Communications', 'Michäel Majeau', 'CAD$10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('5', 'Information', 'François Cardinal', 'Sans Limite', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('6', 'Information', 'Jean-François Bégin', 'CAD$24,999', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('7', 'Information', 'Mélanie Thivierge', 'CAD$24,999', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('8', 'Information', 'Sébastien Rodrigue', 'CAD$10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('9', 'Information', 'Jacques-Olivier Bras', 'CAD$10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('10', 'Information', 'Stéphanie Bérubé', 'CAD$10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('11', 'Information', 'Frédéric Murphy', 'CAD$10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('12', 'Information', 'Isabelle Audet', 'CAD$10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('13', 'Information', 'Violaine Ballivy', 'CAD$10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('14', 'Information', 'Simon Chabot', 'CAD$10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('15', 'Information', 'Jean-François Coderre', 'CAD$10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('16', 'Information', 'Jean-François Tremblay', 'CAD$10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('17', 'Information', 'Yann Pineau', 'CAD$24,999', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('18', 'Éditorial', 'Marius Marin', 'CAD$10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('19', 'Éditeur', 'Guy Crevier', 'Sans Limite', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('20', 'Administration', 'Pierre-Elliot Levasseur', 'Sans Limite', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('21', 'Administration', 'Sylvie Trouilloud', 'CAD$500', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('22', 'Administration', 'Élise Pinard', 'CAD$500', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('23', 'Nuglif', 'François Guy', 'Sans Limite', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('24', 'Nuglif', 'Patrick Piquette', 'CAD$24,999', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('25', 'Capital humain', 'Mireille Larouche', 'Sans Limite', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('26', 'Capital humain', 'Élise Boulerice-Guay', '10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('27', 'Publicité', 'Nicolas Houle', 'CAD$24,999', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('28', 'Publicité', 'Patrick Salois', 'Sans Limite', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('29', 'Publicité', 'Geneviève Roy', 'CAD$24,999', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('30', 'Publicité', 'Stéphane Meloche', 'CAD$10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('31', 'Publicité', 'Anick Beaubien', 'CAD$10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('32', 'Publicité', 'Marc Michaud', 'CAD$10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('33', 'Publicité', 'Claire Bouchard', 'CAD$10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('34', 'Publicité', 'Valérie Beauchesne', 'CAD$10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('35', 'Publicité', 'Julie Arseneau', 'CAD$10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('36', 'Publicité', 'Julie Ghersi', 'CAD$10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('37', 'Publicité', 'Michèle Guilbault', 'CAD$500', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('38', 'Produits Numériques', 'Jean-Marc De Jonghe', 'CAD$24,999', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('39', 'Produits Numériques', 'Marie-Claude Massie', 'CAD$24,999', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('40', 'Produits Numériques', 'Pierre-Philippe Trépanier', 'CAD$24,999', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('41', 'Produits Numériques', 'Vicky Poirier', 'CAD$10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('42', 'TI', 'Patrick Clouâtre', 'Sans Limite', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('43', 'TI', 'François Guy', 'Sans Limite', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('44', 'TI', 'Éric Lanoix', 'CAD$24,999', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('45', 'TI', 'Patrick Dufresne', 'CAD$10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('46', 'TI', 'Louis Pascal Roch', 'CAD$5,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('47', 'TI', 'Richer Francoeur', 'CAD$5,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('48', 'BI', 'Geoffrey Bernard', 'CAD$24,999', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('49', 'BI', 'Catherine Blanchet-Morin', 'CAD$10,000', '2022-07-15 23:22:12');
INSERT INTO "main"."departements" ("id", "departement", "approbe_par", "montant", "last_update") VALUES ('50', 'BI', 'Hervé Mensah', 'CAD$10,000', '2022-07-15 23:22:12');

CREATE VIEW administration AS SELECT * FROM departements WHERE departement='Administration';
CREATE VIEW bi AS SELECT * FROM departements WHERE departement='BI';
CREATE VIEW c_humain AS SELECT * FROM departements WHERE departement='Capital humain';
CREATE VIEW editorial AS SELECT * FROM departements WHERE departement='Éditorial';
CREATE VIEW finance AS SELECT * FROM departements WHERE departement='Finance';
CREATE VIEW information AS SELECT * FROM departements WHERE departement='Information';
CREATE VIEW nuglif AS SELECT * FROM departements WHERE departement='Nuglif';
CREATE VIEW p_numeriques AS SELECT * FROM departements WHERE departement='Produits Numériques';
CREATE VIEW publicite AS SELECT * FROM departements WHERE departement='Publicité';
CREATE VIEW ti AS SELECT * FROM departements WHERE departement='TI';
CREATE VIEW editeur AS SELECT * FROM departements WHERE departement='Éditeur';


INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50500','SoftwareOne','Louis-Pascal Roch','Soumission CA-QUO-131275','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50501','Micro Logic','Louis-Pascal Roch','20200317.1632-01','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50502','Apple','Richer Francoeur','2104251666','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50503','Royal Photo','Carmen Perras','Soumission 263645','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50504','Apple','Louis-Pascal Roch','2104258353','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50505','Apple','Louis-Pascal Roch','2104261100','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50506','DC Group','Louis-Pascal Roch','','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50507','SoftwareOne','Louis-Pascal Roch','Soumission 130691','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50508','SMR','Mario Serio','Soumission DS-00145','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50509','Alfamédia','Louis-Pascal Roch','','Paiement en Euro','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50510','Fournitures de bureau Denis','Mario Serio','10 rubans rouges 2 pouce','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50511','Entrust Datacard','Louis-Pascal Roch','Soumission 408589-1','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50512','PMA','Louis-Pascal Roch','No de dossier 455014','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50513','Apple','Louis-Pascal Roch','Soumission 2104300668','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50514','Fournitures de bureau Denis','Mario Serio','Cale de porte','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50515','Apple','Louis-Pascal Roch','Soumission 2104300673','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50516','Fournitures de bureau Denis','Mario Serio','Masques jetables','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50517','Micro Logic','Louis-Pascal Roch','Q-20200610.0908.01','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50518','Fournitures de bureau Denis','Nathalie Jomphe','Enregistreuse','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50519','Cellcom','Éric Trottier','iPhone SE François Richard','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50520','SoftwareOne','Louis-Pascal Roch','CA-QUO-132563','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50521','Lenovo','Louis-Pascal Roch','Mouse','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50522','Park Place','Louis-Pascal Roch','242400-3','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50523','Apple','Louis-Pascal Roch','Soumission 2104352839','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50524','SoftwareOne','Louis-Pascal Roch','CA-QUO-132813','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50525','Royal Photo','Nathalie Jomphe','','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50526','Levio','Louis-Pascal Roch','','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50527','Micro Logic','Jean Desjardins','','Approuvé par Patrick Clouâtre','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50528','Apple','Jean Desjardins','Proposal 2104367819','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50529','SoftwareOne','Jean Desjardins','CA-QUO-132960','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50530','Tenaquip','Mario Serio','Chariot courrier','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50531','Fournitures de bureau Denis','Mario Serio','Calepins/stylos','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50532','New Relic','Louis-Pascal Roch','','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50533','Fournitures de bureau Denis','Mario Serio','Masques jetables','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50534','Apple','Louis-Pascal Roch','Proposal 2104398688','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50535','Apple','Louis-Pascal Roch','2104408943','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50536','Apple','Louis-Pascal Roch','2104415366','Apprpouvé par Nicolas Houle','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50537','Apple','Louis-Pascal Roch','2104419775','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50538','Les imprimés Triton','Josée Laliberté','','Cartes affaires pour Hélène Pinault','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50538','Cellcom','Patrick Clouâtre','','iPhone SE 2020 pour lui','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50539','SoftwareOne','Louis-Pascal Roch','CA-SCO-134734','approuvé par Jean Desjardin','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50540','Apple','Louis-Pascal Roch','2104419832','Approuvé par Patrick Clouâtre','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50541','Apple','Louis-Pascal Roch','2104426122','Approuvé par Carmen Perras','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50542','SoftwareOne','Louis-Pascal Roch','CA-QUO-133492','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50543','Apple','Louis-Pascal Roch','2104428681','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50544','Lenovo','Louis-Pascal Roch','4296090721','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50545','SoftwareOne','Louis-Pascal Roch','CA-PSI-130564','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('NG50546','Apple','Louis-Pascal Roch','Proposal 2104434517','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50547','SoftwareOne','Louis-Pascal Roch','CA-QUO-133615','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('NG50548','Apple','Louis-Pascal Roch','2104438657','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50549','Apple','Louis-Pascal Roch','2104442135','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50550','Triton','Laurent Benamou','Cartes affaires Simon Dumont','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50551','Apple','Louis-Pascal Roch','2104449904','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50552','Apple','Louis-Pascal Roch','2104445932','Approuvé par Amélie Dubois','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50553','Apple','Louis-Pascal Roch','2104452406','Approuvé par Amélie Dubois','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50554','Canon','Nathalie Jomphe','pour Martin Chamberland','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50555','SoftwareOne','Louis-Pascal Roch','CA-QUO-133878','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50556','Apple','Louis-Pascal Roch','Proposal 2104462696','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50557','New Relic','Louis-Pascal Roch','','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50558','Lenovo','Louis-Pascal Roch','4296300684','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50559','Apple','Louis-Pascal Roch','Proposal 2104470920','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50560','Apple','Louis-Pascal Roch','Proposal 2104477134','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50561','Apple','Louis-Pascal Roch','Proposal 2104494247','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50562','Apple','Louis-Pascal Roch','Proposal 2104494789','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('NG50563','Apple','Louis-Pascal Roch','Proposal 2104497840','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50564','Canon','Nathalie Jomphe','RN113277','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50565','CBCI','Louis-Pascal Roch','QUOTATION 28172-1','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50566','Fournitures de bureau Denis','Mario Serio','Encre pour imprimante 73415-00','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('NG50567','Apple','Louis-Pascal Roch','Proposal 2104501758','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50568','SoftwareOne','Louis-Pascal Roch','CA-SCU-101267','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50569','Park PLace','Louis-Pascal Roch','','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50570','Apple','Louis-Pascal Roch','Proposal 2104504202','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50571','Apple','Louis-Pascal Roch','Proposal 2104505020','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50572','Apple','Louis-Pascal Roch','Proposal 2104507387','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50573','Fournitures de bureau Denis','Mario Serio','Agenda pour Olivier B.','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50574','Cellcom','Amélie Dubois','iPhone pour Guy Crevier','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50575','SoftwareOne','Louis-Pascal Roch','CA-SCU-134495','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50576','Coop UQAM','Louis-Pascal Roch','','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('NG50577','Apple','Louis-Pascal Roch','Proposal 2104518334','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50578','Apple','Louis-Pascal Roch','Proposal 2104519285','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50579','SoftwareOne','Sandy Filc','CA-QUO-134511','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50580','Apple','Louis-Pascal Roch','Proposal 2104528643','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50581','Royal Photo','Nathalie Jomphe','R20199','Approuvé par Carmen Perras','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50582','Royal Photo','Nathalie Jomphe','QUO-1386','Approuvé par Carmen Perras','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50583','Cellcom','Mario Serio','Pour Angela Kourouklis','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50584','Cellcom','Nathalie Jomphe','SE 20200 pour Olivier Jean','Approuvé par Carmen Perras','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50585','Dell','Louis-Pascal Roch','Quotation 81364137','Approuvé par François Guy','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50586','Royal Photo','Nathalie Jomphe','QUO-1340','Approuvé par Carmen Perras','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50587','Cellcom','Nathalie Jomphe','Pour François Roy','Approuvé par Carmen Perras','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50588','Royal Photo','Nathalie Jomphe','QUO-1420','Approuvé par Carmen Perras','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50589','Apple','Louis-Pascal Roch','Proposal 2104557341','Même PO pour 2 fournisseurs différents','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50589','Royal Photo','Nathalie Jomphe','QUO-1426','Même PO pour 2 fournisseurs différents','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50590','Apple','Louis-Pascal Roch','Proposal 2104559941','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50591','SoftwareOne','Louis-Pascal Roch','CA-QUO-135044','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50592','ITI INC.','Louis-Pascal Roch','Soumission 220588','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50593','ITI INC.','Louis-Pascal Roch','Soumission 220697','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50594','Apple','Louis-Pascal Roch','Proposal 2104570311','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50595','Royal Photo','Nathalie Jomphe','QUO-1589','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50596','ITI INC.','Louis-Pascal Roch','','Approuvé par Nicolas Houle','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50597','ITI INC.','Louis-Pascal Roch','','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50598','ITI INC.','Louis-Pascal Roch','','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50599','Cellcom','Nathalie Jomphe','Cellulaire Patrick Sansfaçon','Approuvé par Amélie Dubois','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50600','ITI INC.','Louis-Pascal Roch','Proposal 221871','Approuvé par Patrick Dufresne','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50601','SoftwareOne','Louis-Pascal Roch','Quote CA-QUO-135423','Approuvé par Patrick Dufresne','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50602','Dell','Louis-Pascal Roch','Quote 81866246','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50603','ITI INC.','Louis-Pascal Roch','Proposal 222577','Approuvé par Geoffrey Bernard','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50604','Cellcom','Stéphanie Forest','iPhone pour Claudia Cordova','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50605','Fournitures de bureau Denis','Stéphanie Forest','','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50606','Fournitures de bureau Denis','Mario Serio','Feuilles blanches','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50607','Camtec Photo','Nathalie Jomphe','Remplacement courroies','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50608','COOP UQAM','Louis-Pascal Roch','3 soumissions différentes','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50609','Apple','Louis-Pascal Roch','Proposal 2104632480','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50610','Fournitures de bureau Denis','Mario Serio','Cahiers et stylos','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50611','Les imprimés Triton','Mario Serio','Enveloppes 80-993A','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50612','Apple','Louis-Pascal Roch','Proposal 2110021042','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50613','Apple','Louis-Pascal Roch','Proposal 2110019115','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50614','Apple','Louis-Pascal Roch','Proposal 2110019116','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50615','Dell','Louis-Pascal Roch','Quote 82329426','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50617','Royal Photo','Nathalie Jomphe','','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50618','Apple','Louis-Pascal Roch','Proposal 2110023785','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50619','Royal Photo','Louis-Pascal Roch','QUO-1939','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50620','Apple','Louis-Pascal Roch','Proposal 2110027231','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50621','Lenovo','Louis-Pascal Roch','Proposal 4600202585','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50622','Apple','Louis-Pascal Roch','Proposal 2110029761','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50623','AKT Information','Nathalie Jomphe','Masques','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50624','AKT Information','Nathalie Jomphe','Essais masques','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50625','Apple','Louis-Pascal Roch','Proposal 2110046059','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50626','ITI INC.','Louis-Pascal Roch','Soumission 227657','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50627','Lenovo','Louis-Pascal Roch','','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50628','Dell','Louis-Pascal Roch','Quote 82329426','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50629','Royal Photo','Nathalie Jomphe','Quo-2070','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50630','ITI INC.','Louis-Pascal Roch','Soumission 228238','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50631','Lenovo','Louis-Pascal Roch','Soumission 4600353401','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50632','ITI INC.','Louis-Pascal Roch','Soumission 228167','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50633','Apple','Louis-Pascal Roch','Proposal 2110058318','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50634','Apple','Louis-Pascal Roch','Proposal 210058303','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50635','Apple','Louis-Pascal Roch','Proposal 2110061669','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50636','ITI INC.','Louis-Pascal Roch','Soumission 229422','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50637','SoftwareOne','Louis-Pascal Roch','CA-QUO-137175','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50638','Apple','Louis-Pascal Roch','Proposal 2110071411','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50639','JAMF','Éric Lanoix','Approuvé par Patrick Clouâtre','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50640','ITI INC.','Louis-Pascal Roch','Soumission 229607','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50641','Lenovo','Louis-Pascal Roch','Quote ID: 4600505931','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50642','ITI INC.','Louis-Pascal Roch','Soumission 230005','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50643','Apple','Louis-Pascal Roch','Proposal 2110091512','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50644','Cellcom','Nathalie Jomphe','Cel pour Mélanie Thivierge','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50645','Apple','Louis-Pascal Roch','Proposal 2110096127','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('NG50646','Apple','Louis-Pascal Roch','Proposal 2110112444','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50647','Apple','Louis-Pascal Roch','Proposal 2110116407','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50648','Cisco Meraki AC Adapter','Louis-Pascal Roch','MA-PWR-30W-US','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50649','ITI INC.','Louis-Pascal Roch','Soumission 232049','Approuvé Par Eric Lanoix','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50650','MicroLogic','Patrick Dufresne','Proposal EST17719-9','Aprouvé par François Guy','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50651','Lenovo','Louis-Pascal Roch','4600708866','Approuvé par Partrick Dufresne','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50652','ITI INC.','Louis-Pascal Roch','Soumission 232229','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50653','Camtec Photo','Nathalie Jomphe','Soumission 239981','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50654','ITI INC.','Louis-Pascal Roch','Soumission 232540','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50655','Apple','Louis-Pascal Roch','2110125095','Approuvé par Patrick Clouâtre','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50656','ITI INC.','Louis-Pascal Roch','','Approuvé par Patrick Clouâtre','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50657','Apple','Louis-Pascal Roch','Proposal 2110134150','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50658','Triton','Isabel Richer','Cartes affaires Patrick Salois','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50659','ITI INC.','Louis-Pascal Roch','Soumission 232869','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50660','Cellcom','Mario Serio','Cel pour Mackenzie Sylvestre','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50661','ITI INC.','Louis-Pascal Roch','Soumission 233033','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50662','Entrust Datacard','Daphnée Chabalier','','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50663','SoftwareOne','Louis-Pascal Roch','Quote-Ca-QUO-138135','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50664','Royal Photo','Stéphanie Bérubé','Réparation','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50665','SoftwareOne','Louis-Pascal Roch','CA-QUO-138177','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50666','ITI INC.','Louis-Pascal Roch','Soumission 233789','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50667','SoftwareOne','Louis-Pascal Roch','Quote-Ca-QUO-138199','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50668','Apple','Louis-Pascal Roch','Proposal 2110165075','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('NG50669','Apple','Louis-Pascal Roch','Proposal 2110165076','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50670','Apple','Louis-Pascal Roch','Proposal 210166392','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50671','Cellcom','Mario Serio','Pour Julie Ghersi','PO peut-être pas inscrit sur facture','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50672','Cellcom','Mario Serio','Pour PEL','PO peut-être pas inscrit sur facture','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50673','Royal Photo','Nathalie Jomphe','Soumission QUO-2623','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('NG50674','Apple','Louis-Pascal Roch','Proposal 2110175860','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50675','Apple','Louis-Pascal Roch','Proposal 2110176586','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50676','Canon','Nathalie Jomphe','','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50677','ITI INC.','Louis-Pascal Roch','Soumission 230058','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50678','Fournitures de bureau Denis','Mario Serio','','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50679','SoftwareOne','Éric Lanoix','CA-QUO-138504','36K','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50680','JAMF','Patrick Dufresne','Q-368779','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50681','Cellcom','Yann Pineau','1 SIM','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50682','Royal Photo','Nathalie Jomphe','QUO-2571-2','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50683','Royal Photo','Nathalie Jomphe','QUO-2684','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50684','Apple','Louis-Pascal Roch','Proposal 2110193074','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50685','Victrix','Patrick Dufresne','','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50686','Apple','Louis-Pascal Roch','Proposal 2110200950','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('NG50687','Apple','Louis-Pascal Roch','Proposal 2110200980','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50688','ITI INC.','Louis-Pascal Roch','Soumission 236076','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50689','Apple','Louis-Pascal Roch','Proposal 2110206697','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50690','Lenovo','Louis-Pascal Roch','4601135161','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50691','ITI INC.','Patrick Dufresne','236405','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50692','Apple','Louis-Pascal Roch','2110215699','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('NG50693','Apple','Louis-Pascal Roch','2110217633','Patrick Dufresne','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50694','Apple','Louis-Pascal Roch','2110218907','Patrick Dufresne','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50695','ITI INC.','Louis-Pascal Roch','236723','Eric Lanoix','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50696','Apple','Louis-Pascal Roch','Proposal 2110234445','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50697','Site 24/7','Éric Lanoix','','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50698','SoftwareOne','Louis-Pascal Roch','CA-QUO-139228','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50699','Park Place','Éric Lanoix','377214','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50700','ITI INC.','Louis-Pascal Roch','Soumission 237645','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50701','Lenovo','Louis-Pascal Roch','Quote 4601339745','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50702','Apple','Louis-Pascal Roch','Soumission 2110249713','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50703','ITI INC.','Louis-Pascal Roch','Soumission 238343','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50704','ITI INC.','Louis-Pascal Roch','Soumission 238439','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50705','ITI INC.','Louis-Pascal Roch','Soumission  238474','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50706','SoftwareOne','Patrick Dufresne','CA-QUO-139413','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('NG50707','Apple','Louis-Pascal Roch','Soumission 2110269196','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50708','SoftwareOne','Louis-Pascal Roch','3 licences','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50709','SoftwareOne','Louis-Pascal Roch','CA-QUO-139646','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50710','ITI INC.','Louis-Pascal Roch','Soumission 238982','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50711','SoftwareOne','Louis-Pascal Roch','CA-QUO-139727','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('NG50712','Apple','Louis-Pascal Roch','Proposal 2110294288','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50713','Apple','Louis-Pascal Roch','Proposal 2110295401','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50714','Micro Logic','Patrick Dufresne','Proposition Q20210830.1029-01','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50715','ITI INC.','Louis-Pascal Roch','','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50716','Apple','Louis-Pascal Roch','Proposal 2110306413','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50717','ITI INC.','Louis-Pascal Roch','Soumission 240176','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50718','Royal Photo','Nathalie Jomphe','Boitiers Alain Roberge','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50719','ITI INC.','Louis-Pascal Roch','Soumission 240172','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50720','Apple','Louis-Pascal Roch','Proposal 2110311621','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50721','ITI INC.','Louis-Pascal Roch','Soumission 240483','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50722','ITI INC.','Ali Anwar','Soumission 241009','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50723','ITI INC.','Louis-Pascal Roch','Soumission 241034','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50724','Apple','Louis-Pascal Roch','Proposal 2110327624','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50725','Apple','Louis-Pascal Roch','Proposal 2110327678','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50726','ITI INC.','Louis-Pascal Roch','Soumission 241182','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50727','Cellcom','Mélanie Thivierge','Cellulaire Sébastien Rodrigue','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50728','ITI INC.','Louis-Pascal Roch','Soumission 241298','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50729','Royal Photo','Nathalie Jomphe','Soumission QUO-3232','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50730','Cellcom','Mario Serio','iPhone Anick Beaubien','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('NG50731','Apple','Louis-Pascal Roch','Proposition 2110346522','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50732','Apple','Louis-Pascal Roch','Proposition 2110346524','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50733','CBCI','Louis-Pascal Roch','30429011021','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50734','ITI INC.','Louis-Pascal Roch','Soumission 241998','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50735','ITI INC.','Louis-Pascal Roch','Soumission 242057','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50736','Apple','Louis-Pascal Roch','Soumission 2110348547','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50737','ITI INC.','Louis-Pascal Roch','Soumission 242075','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50738','ITI INC.','Louis-Pascal Roch','Soumission 241138','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('NG50739','Apple','Louis-Pascal Roch','Proposition 2110352149','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50740','SoftwareOne','Louis-Pascal Roch','Quote-CA-QUO-140509','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50741','Camtec','Nathalie Jomphe','Quotation 240495','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50742','ITI INC.','Louis-Pascal Roch','Soumission 242245','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50743','Royal Photo','Nathalie Jomphe','QUO-3356','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50744','ITI INC.','Louis-Pascal Roch','Soumission 242716','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50745','SoftwareOne','Louis-Pascal Roch','QUOTE-CA-QUO-140635','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50746','Royal Photo','Nathalie Jomphe','Réparation objectif Hugo-Sébastien','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50747','Royal Photo','Nathalie Jomphe','QUO-3387','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50748','Apple','Louis-Pascal Roch','Soumission 2110372662','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50749','Apple','Louis-Pascal Roch','Soumission 2110362028','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50750','Canon','Nathalie Jomphe','l’objectif 24-70mm de Marco Campanozzi','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50751','Lenovo','Louis-Pascal Roch','4601863065','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50752','Egyde Conseils','Patrick Dufresne','QUO-9814122-X7Q5W5-0','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50753','ITI INC.','Louis-Pascal Roch','Soumission 243240','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50754','Canon','Nathalie Jomphe','Réparation objectif','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50755','Apple','Louis-Pascal Roch','Soumission 2110388207','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50756','Apple','Louis-Pascal Roch','Soumission2110388515','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50757','Apple','Louis-Pascal Roch','Soumission 2110393641','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50758','ITI INC.','Louis-Pascal Roch','Soumission 243163','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50759','Apple','Louis-Pascal Roch','Soumission2110391574','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50760','Royal Photo','Nathalie Jomphe','QUO-3351-1','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50761','Royal Photo','Nathalie Jomphe','QUO-3231-3','','Complet');
INSERT INTO "main"."liste_de_po" ("numero_de_po","fournisseur","demande_par","description","commentaire","statut") VALUES ('LP50762','Royal Photo','Nathalie Jomphe','QUO-3231-2','','Complet');

CREATE VIEW liste_complet AS SELECT * FROM liste_de_po;